sudo: required
services:
  - docker

before_install:
  - docker build -t eifelmattes/docker-react -f Dockerfile.dev .

script:
  - docker run eifelmattes/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-us-west-2-404630354009
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_Access_Key
  secret_access_key:
    secure: "$AWS_Secret_Key"
